"""Alpha Decay Monitor logic."""

import logging
from typing import List

from algoforge.backtest.models import TradePnL
from algoforge.backtest.metrics import calculate_metrics
import pandas as pd

from algoforge.decay.models import BaselineManifest, HealthReport, HealthStatus

logger = logging.getLogger(__name__)


class AlphaDecayMonitor:
    """Monitors live performance against backtest baselines to throttle failing strategies."""

    def evaluate_family_health(
        self,
        family_name: str,
        recent_trades: List[TradePnL],
        equity_curve_30d: pd.Series,
        baseline: BaselineManifest
    ) -> HealthReport:
        """Evaluate the health of a signal family based on recent trades.

        Args:
            family_name: The name of the signal family.
            recent_trades: A list of recent trades executed by this family.
            equity_curve_30d: The 30-day equity curve generated by this family's trades.
            baseline: The expected performance manifest from the backtest.

        Returns:
            A HealthReport containing the status and the conviction multiplier.
        """
        # If no trades have happened recently, default to healthy
        if not recent_trades or len(recent_trades) < 5:
            return HealthReport(
                family_name=family_name,
                status=HealthStatus.HEALTHY,
                multiplier=1.0,
                current_hit_rate=baseline.expected_hit_rate,
                current_average_r=baseline.expected_average_r,
                current_30d_sharpe=baseline.expected_sharpe,
                hit_rate_z_score=0.0,
                reason="Insufficient recent trade data. Defaulting to healthy."
            )

        # 1. Calculate Current Metrics
        wins = [t for t in recent_trades if t.pnl_amount > 0]
        current_hit_rate = len(wins) / len(recent_trades)
        
        # We approximate 'R' by looking at the pnl_pct for simplicity in this implementation.
        # In a full implementation, TradePnL would explicitly track initial risk per trade.
        # Here we just use the average PnL amount as a proxy for the R check.
        current_average_r = sum(t.pnl_pct for t in recent_trades) / len(recent_trades)

        # Calculate 30-day Sharpe (requires equity curve)
        metrics = calculate_metrics(recent_trades, equity_curve_30d, initial_capital=equity_curve_30d.iloc[0])
        current_30d_sharpe = metrics.sharpe_ratio

        # 2. Calculate Z-Score for Hit Rate
        # z = (X - μ) / σ
        std_dev = max(baseline.hit_rate_std_dev, 0.01) # Prevent division by zero
        hit_rate_z_score = (current_hit_rate - baseline.expected_hit_rate) / std_dev

        # 3. Evaluate Health Rules (Order matters: most severe penalty first)
        
        # Rule 1: Catastrophic decay - Hit Rate dropped > 2σ
        if hit_rate_z_score < -2.0:
            logger.warning(
                "[%s] PAUSED: Hit rate deviation > 2σ (Z=%.2f). Live: %.2f, Expected: %.2f",
                family_name, hit_rate_z_score, current_hit_rate, baseline.expected_hit_rate
            )
            return HealthReport(
                family_name, HealthStatus.PAUSED, 0.0,
                current_hit_rate, current_average_r, current_30d_sharpe, hit_rate_z_score,
                reason="Hit rate deviation > 2σ"
            )

        # Rule 2: Catastrophic decay - Average R is terrible
        if current_average_r < baseline.expected_average_r * 0.5:
            logger.warning(
                "[%s] PAUSED: Average R dropped below 50%% of expected. Live: %.4f, Expected: %.4f",
                family_name, current_average_r, baseline.expected_average_r
            )
            return HealthReport(
                family_name, HealthStatus.PAUSED, 0.0,
                current_hit_rate, current_average_r, current_30d_sharpe, hit_rate_z_score,
                reason="Average R < 0.5R expected"
            )

        # Rule 3: Degradation - 30-day Sharpe is negative
        if current_30d_sharpe < 0:
            logger.info(
                "[%s] DEGRADED: 30-day Sharpe is negative (%.2f). Throttling weight 50%%.",
                family_name, current_30d_sharpe
            )
            return HealthReport(
                family_name, HealthStatus.DEGRADED, 0.5,
                current_hit_rate, current_average_r, current_30d_sharpe, hit_rate_z_score,
                reason="30-day Sharpe < 0"
            )

        # Passed all checks
        return HealthReport(
            family_name, HealthStatus.HEALTHY, 1.0,
            current_hit_rate, current_average_r, current_30d_sharpe, hit_rate_z_score,
            reason="Operating normally."
        )
