"""Universe Engine — Dynamic asset discovery and scoring.

Implements Freqtrade-inspired pairlist plugins.
The universe is generated by passing through a pipeline of filters.
"""

from __future__ import annotations

import abc
import asyncio
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

import requests
import structlog

from algoforge.core.constants import Timeframe
from algoforge.core.models import OHLCV
from algoforge.engine.state import AssetMemory, SystemState, log_msg

logger = structlog.get_logger(__name__)

STABLECOIN_FRAGMENTS = frozenset(
    ["USDC", "FDUSD", "TUSD", "USD1", "USDD", "BUSD", "DAI", "USDE"]
)


class PairlistPlugin(abc.ABC):
    """Base class for universe pairlist plugins."""
    
    @abc.abstractmethod
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        """Filter and/or score the universe."""
        pass


class VolumePairList(PairlistPlugin):
    """Base pairlist: selects top N pairs by volume, excluding stablecoins."""
    
    def __init__(self, limit: int = 75):
        self.limit = limit
        
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        filtered = []
        for asset in universe:
            sym = asset["symbol"]
            if any(stable in sym for stable in STABLECOIN_FRAGMENTS):
                continue
            # Ensure liquidity minimum
            if asset.get("volume", 0) < state.discovery_config.min_liquidity:
                continue
            filtered.append(asset)
            
        filtered.sort(key=lambda x: x.get("volume", 0), reverse=True)
        return filtered[:self.limit]


class VolatilityFilter(PairlistPlugin):
    """Filters out assets that are too stable or insanely volatile."""
    
    def __init__(self, min_vol_pct: float = 1.0, max_vol_pct: float = 20.0):
        self.min_vol = min_vol_pct
        self.max_vol = max_vol_pct
        
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        filtered = []
        for asset in universe:
            high = asset.get("high", 0)
            low = asset.get("low", 0)
            price = asset.get("last_price", 1)
            if price <= 0:
                continue
            
            vol_pct = (high - low) / price * 100
            if self.min_vol <= vol_pct <= self.max_vol:
                filtered.append(asset)
        return filtered


class PerformanceFilter(PairlistPlugin):
    """Scores remaining assets based on trend strength and historical edge."""
    
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        scored = []
        for asset in universe:
            sym = asset["symbol"]
            trend_strength = asset.get("price_change_pct", 0)
            
            # Persistence Modifier
            if sym not in state.asset_memory:
                state.asset_memory[sym] = AssetMemory(symbol=sym)
            mem = state.asset_memory[sym]

            base_score = trend_strength + 50.0  # Normalize around 50
            final_score = round(base_score + min(mem.cycles_selected * 2.0, 10.0), 2)
            
            trend_str = (
                "UP" if final_score > mem.last_score + 1
                else "DOWN" if final_score < mem.last_score - 1
                else "FLAT"
            )
            mem.score_trend = trend_str
            mem.last_score = final_score

            scored.append({
                "symbol": sym,
                "score": final_score,
                "trend": trend_str,
                "persistence": f"{mem.cycles_selected} cycles",
                "status": "EVALUATING",
                **asset
            })
            
        return scored


class PairListManager:
    """Manages the pairlist plugin pipeline."""
    
    def __init__(self):
        self.plugins = [
            VolumePairList(limit=100),
            VolatilityFilter(min_vol_pct=0.5, max_vol_pct=15.0),
            PerformanceFilter()
        ]
        
    def generate_universe(self, state: SystemState, raw_data: list[dict]) -> list[dict]:
        universe = raw_data
        for plugin in self.plugins:
            universe = plugin.filter(state, universe)
        return universe


# Singleton instance for the trading loop
_pairlist_manager = PairListManager()


def score_universe(state: SystemState, universe: list[dict]) -> list[dict]:
    """Score all assets using the plugin pipeline.
    
    Maintains backward compatibility with trading_loop.py.
    """
    return _pairlist_manager.generate_universe(state, universe)


def select_top_assets(state: SystemState, scores: list[dict]) -> list[dict]:
    """Select top-K assets above dynamic threshold.

    Updates asset memory persistence counters.
    """
    scores.sort(key=lambda x: x.get("score", 0), reverse=True)

    above_threshold = [
        s for s in scores
        if s.get("score", 0) >= state.discovery_config.dynamic_threshold
    ]
    selected = above_threshold[:state.discovery_config.max_active_assets]

    for s in scores:
        mem = state.asset_memory[s["symbol"]]
        if s in selected:
            mem.cycles_selected += 1
            s["status"] = "ACTIVE"
        else:
            mem.cycles_selected = max(0, mem.cycles_selected - 1)

    return selected


def fetch_historical_klines(symbol: str) -> list[OHLCV]:
    """Fetch 250 historical 1m klines from Binance REST API."""
    try:
        url = f"https://api.binance.com/api/v3/klines?symbol={symbol}&interval=1m&limit=250"
        resp = requests.get(url, timeout=8)
        data = resp.json()
        return [OHLCV(
            symbol=symbol,
            timeframe=Timeframe.M1,
            timestamp=datetime.fromtimestamp(r[0] / 1000, tz=timezone.utc),
            open=float(r[1]),
            high=float(r[2]),
            low=float(r[3]),
            close=float(r[4]),
            volume=float(r[5])
        ) for r in data]
    except Exception as e:
        logger.error(f"Failed to fetch historical klines for {symbol}: {e}")
        return []


async def prefetch_klines(state: SystemState) -> None:
    """Pre-fetch historical klines in parallel for newly selected assets."""
    symbols_to_fetch = [
        sym for sym in state.selected_assets
        if sym not in state.kline_buffers
    ]
    if not symbols_to_fetch:
        return

    # Check persistence cache first (Phase 4)
    cache_hits = 0
    symbols_to_download = []
    
    for sym in symbols_to_fetch:
        if state.persistence.has_klines(sym, "1m", min_count=200):
            cached_data = state.persistence.load_klines(sym, "1m", limit=250)
            candles = [OHLCV(
                symbol=sym, timeframe=Timeframe.M1,
                timestamp=datetime.fromisoformat(c["timestamp"]),
                open=c["open"], high=c["high"], low=c["low"],
                close=c["close"], volume=c["volume"]
            ) for c in cached_data]
            state.kline_buffers[sym] = candles
            cache_hits += 1
        else:
            symbols_to_download.append(sym)

    if cache_hits > 0:
        log_msg(state, f"Loaded {cache_hits} kline histories from local SQLite cache.")

    if not symbols_to_download:
        return

    log_msg(state, f"Pre-fetching {len(symbols_to_download)} kline histories in parallel via REST...")
    loop = asyncio.get_event_loop()
    with ThreadPoolExecutor(max_workers=min(len(symbols_to_download), 10)) as pool:
        results = await loop.run_in_executor(
            None,
            lambda: {sym: fetch_historical_klines(sym) for sym in symbols_to_download}
        )
    
    for sym, candles in results.items():
        if candles:
            state.kline_buffers[sym] = candles
            # Save newly downloaded to cache
            state.persist_klines(sym)
            
    log_msg(
        state,
        f"Kline REST pre-fetch complete: {sum(len(v) for v in results.values())} candles loaded."
    )
