"""Universe Engine — Dynamic asset discovery and scoring.

Implements Freqtrade-inspired pairlist plugins.
The universe is generated by passing through a pipeline of filters.
"""

from __future__ import annotations

import abc
import asyncio
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

import requests
import structlog

from algoforge.core.constants import Timeframe
from algoforge.core.models import OHLCV
from algoforge.engine.state import AssetMemory, SystemState, log_msg

logger = structlog.get_logger(__name__)

STABLECOIN_FRAGMENTS = frozenset(
    ["USDC", "FDUSD", "TUSD", "USD1", "USDD", "BUSD", "DAI", "USDE"]
)

# Meme / ultra-low-quality tokens that should never be traded.
# Add symbols here to permanently exclude them from the universe.
MEME_BLACKLIST = frozenset([
    "DOGSUSDT", "SHIBUSDT", "PEPEUSDT", "FLOKIUSDT", "BONKUSDT",
    "MEMECOINUSDT", "BABYDOGEUSDT", "ELONUSDT", "SAFEUSDT",
    "LUNCUSDT", "LUNAUSDT", "USTCUSDT",
])


class PairlistPlugin(abc.ABC):
    """Base class for universe pairlist plugins."""
    
    @abc.abstractmethod
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        """Filter and/or score the universe."""
        pass


class VolumePairList(PairlistPlugin):
    """Base pairlist: selects top N pairs by volume, excluding stablecoins and blacklisted memes."""
    
    def __init__(self, limit: int = 75):
        self.limit = limit
        
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        filtered = []
        for asset in universe:
            sym = asset["symbol"]
            # Exclude stablecoins
            if any(stable in sym for stable in STABLECOIN_FRAGMENTS):
                continue
            # Exclude blacklisted meme coins
            if sym in MEME_BLACKLIST:
                continue
            # Ensure liquidity minimum
            if asset.get("volume", 0) < state.discovery_config.min_liquidity:
                continue
            filtered.append(asset)
            
        filtered.sort(key=lambda x: x.get("volume", 0), reverse=True)
        return filtered[:self.limit]


class MarketCapFilter(PairlistPlugin):
    """Rejects assets below a minimum market cap threshold.
    
    Binance doesn't directly serve market cap, but we approximate it from
    `circulating_supply * last_price` or fall back to using 24h quote volume
    as a rough proxy (top coins trade >$100M/day).
    """
    
    def __init__(self, min_market_cap_proxy: float = 50_000_000.0):
        self.min_mcap = min_market_cap_proxy
        
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        filtered = []
        for asset in universe:
            # Use quoteVolume (24h USDT volume) as a market cap proxy.
            # Legitimate large-cap coins trade > $50M/day in USDT volume.
            quote_vol = asset.get("quoteVolume", asset.get("volume", 0))
            if quote_vol >= self.min_mcap:
                filtered.append(asset)
        return filtered


class SpreadFilter(PairlistPlugin):
    """Rejects assets with excessively wide bid/ask spreads (illiquid)."""
    
    def __init__(self, max_spread_pct: float = 0.5):
        self.max_spread_pct = max_spread_pct
        
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        filtered = []
        for asset in universe:
            bid = asset.get("bid", 0)
            ask = asset.get("ask", 0)
            if bid > 0 and ask > 0:
                spread_pct = (ask - bid) / ask * 100
                if spread_pct > self.max_spread_pct:
                    continue
            filtered.append(asset)
        return filtered


class VolatilityFilter(PairlistPlugin):
    """Filters out assets that are too stable or insanely volatile."""
    
    def __init__(self, min_vol_pct: float = 1.0, max_vol_pct: float = 15.0):
        self.min_vol = min_vol_pct
        self.max_vol = max_vol_pct
        
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        filtered = []
        for asset in universe:
            high = asset.get("high", 0)
            low = asset.get("low", 0)
            price = asset.get("last_price", 1)
            if price <= 0:
                continue
            
            vol_pct = (high - low) / price * 100
            if self.min_vol <= vol_pct <= self.max_vol:
                asset["_vol_pct"] = round(vol_pct, 2)
                filtered.append(asset)
        return filtered


class QualityScorer(PairlistPlugin):
    """Multi-factor quality scoring — replaces the old naive price_change_pct scorer.
    
    Factors (weighted):
        1. Volume Rank (25%) — higher 24h volume = higher score
        2. Volatility Quality (20%) — moderate volatility scores best (4-8% sweet spot)
        3. Momentum Quality (25%) — positive but not extreme trend strength
        4. Persistence (15%) — assets that have been selected before get a bonus
        5. Spread Tightness (15%) — tighter spread = better quality
    
    Final score is 0-100. Threshold should be ~55 to be meaningful.
    """
    
    def filter(self, state: SystemState, universe: list[dict]) -> list[dict]:
        if not universe:
            return []
        
        # 1. Volume Rank Score (0-25)
        volumes = [a.get("volume", 0) for a in universe]
        max_vol = max(volumes) if volumes else 1
        
        scored = []
        for asset in universe:
            sym = asset["symbol"]
            
            # Persistence tracking
            if sym not in state.asset_memory:
                state.asset_memory[sym] = AssetMemory(symbol=sym)
            mem = state.asset_memory[sym]
            
            # Factor 1: Volume rank (0-25)
            vol = asset.get("volume", 0)
            vol_score = (vol / max_vol) * 25.0 if max_vol > 0 else 0.0
            
            # Factor 2: Volatility quality (0-20) — sweet spot is 3-8%
            vol_pct = asset.get("_vol_pct", 5.0)
            if 3.0 <= vol_pct <= 8.0:
                volatility_score = 20.0
            elif 1.5 <= vol_pct < 3.0 or 8.0 < vol_pct <= 12.0:
                volatility_score = 12.0
            else:
                volatility_score = 5.0
            
            # Factor 3: Momentum quality (0-25) — positive but not parabolic
            trend_pct = asset.get("price_change_pct", 0)
            if 0.5 <= trend_pct <= 5.0:
                momentum_score = 25.0  # Healthy uptrend
            elif 0.0 <= trend_pct < 0.5:
                momentum_score = 15.0  # Flat-ish, could break either way
            elif 5.0 < trend_pct <= 10.0:
                momentum_score = 18.0  # Strong but risky
            elif trend_pct > 10.0:
                momentum_score = 8.0   # Parabolic — likely to dump
            elif -3.0 <= trend_pct < 0.0:
                momentum_score = 10.0  # Slight dip, potential bounce
            else:
                momentum_score = 3.0   # Crashing — avoid
            
            # Factor 4: Persistence (0-15)
            persistence_score = min(mem.cycles_selected * 3.0, 15.0)
            
            # Factor 5: Spread quality (0-15)
            bid = asset.get("bid", 0)
            ask = asset.get("ask", 0)
            if bid > 0 and ask > 0:
                spread_pct = (ask - bid) / ask * 100
                if spread_pct < 0.05:
                    spread_score = 15.0
                elif spread_pct < 0.1:
                    spread_score = 12.0
                elif spread_pct < 0.3:
                    spread_score = 8.0
                else:
                    spread_score = 3.0
            else:
                spread_score = 8.0  # Unknown spread, neutral
            
            final_score = round(
                vol_score + volatility_score + momentum_score +
                persistence_score + spread_score, 2
            )
            
            trend_str = (
                "UP" if final_score > mem.last_score + 1
                else "DOWN" if final_score < mem.last_score - 1
                else "FLAT"
            )
            mem.score_trend = trend_str
            mem.last_score = final_score
            
            scored.append({
                "symbol": sym,
                "score": final_score,
                "score_breakdown": {
                    "volume": round(vol_score, 1),
                    "volatility": round(volatility_score, 1),
                    "momentum": round(momentum_score, 1),
                    "persistence": round(persistence_score, 1),
                    "spread": round(spread_score, 1),
                },
                "trend": trend_str,
                "persistence": f"{mem.cycles_selected} cycles",
                "status": "EVALUATING",
                **asset
            })
            
        return scored


class PairListManager:
    """Manages the pairlist plugin pipeline."""
    
    def __init__(self):
        self.plugins = [
            VolumePairList(limit=100),
            MarketCapFilter(min_market_cap_proxy=50_000_000.0),
            SpreadFilter(max_spread_pct=0.5),
            VolatilityFilter(min_vol_pct=0.5, max_vol_pct=15.0),
            QualityScorer(),
        ]
        
    def generate_universe(self, state: SystemState, raw_data: list[dict]) -> list[dict]:
        universe = raw_data
        for plugin in self.plugins:
            universe = plugin.filter(state, universe)
        return universe


# Singleton instance for the trading loop
_pairlist_manager = PairListManager()


def score_universe(state: SystemState, universe: list[dict]) -> list[dict]:
    """Score all assets using the plugin pipeline.
    
    Maintains backward compatibility with trading_loop.py.
    """
    return _pairlist_manager.generate_universe(state, universe)


def select_top_assets(state: SystemState, scores: list[dict]) -> list[dict]:
    """Select top-K assets above dynamic threshold.

    Updates asset memory persistence counters.
    """
    scores.sort(key=lambda x: x.get("score", 0), reverse=True)

    above_threshold = [
        s for s in scores
        if s.get("score", 0) >= state.discovery_config.dynamic_threshold
    ]
    selected = above_threshold[:state.discovery_config.max_active_assets]

    for s in scores:
        mem = state.asset_memory[s["symbol"]]
        if s in selected:
            mem.cycles_selected += 1
            s["status"] = "ACTIVE"
        else:
            mem.cycles_selected = max(0, mem.cycles_selected - 1)

    return selected


def fetch_historical_klines(symbol: str) -> list[OHLCV]:
    """Fetch 250 historical 1m klines from Binance REST API."""
    try:
        url = f"https://api.binance.com/api/v3/klines?symbol={symbol}&interval=1m&limit=250"
        resp = requests.get(url, timeout=8)
        data = resp.json()
        return [OHLCV(
            symbol=symbol,
            timeframe=Timeframe.M1,
            timestamp=datetime.fromtimestamp(r[0] / 1000, tz=timezone.utc),
            open=float(r[1]),
            high=float(r[2]),
            low=float(r[3]),
            close=float(r[4]),
            volume=float(r[5])
        ) for r in data]
    except Exception as e:
        logger.error(f"Failed to fetch historical klines for {symbol}: {e}")
        return []


async def prefetch_klines(state: SystemState) -> None:
    """Pre-fetch historical klines in parallel for newly selected assets."""
    symbols_to_fetch = [
        sym for sym in state.selected_assets
        if sym not in state.kline_buffers
    ]
    if not symbols_to_fetch:
        return

    # Check persistence cache first (Phase 4)
    cache_hits = 0
    symbols_to_download = []
    
    for sym in symbols_to_fetch:
        if state.persistence.has_klines(sym, "1m", min_count=200):
            cached_data = state.persistence.load_klines(sym, "1m", limit=250)
            candles = [OHLCV(
                symbol=sym, timeframe=Timeframe.M1,
                timestamp=datetime.fromisoformat(c["timestamp"]),
                open=c["open"], high=c["high"], low=c["low"],
                close=c["close"], volume=c["volume"]
            ) for c in cached_data]
            state.kline_buffers[sym] = candles
            cache_hits += 1
        else:
            symbols_to_download.append(sym)

    if cache_hits > 0:
        log_msg(state, f"Loaded {cache_hits} kline histories from local SQLite cache.")

    if not symbols_to_download:
        return

    log_msg(state, f"Pre-fetching {len(symbols_to_download)} kline histories in parallel via REST...")
    loop = asyncio.get_event_loop()
    with ThreadPoolExecutor(max_workers=min(len(symbols_to_download), 10)) as pool:
        results = await loop.run_in_executor(
            None,
            lambda: {sym: fetch_historical_klines(sym) for sym in symbols_to_download}
        )
    
    for sym, candles in results.items():
        if candles:
            state.kline_buffers[sym] = candles
            # Save newly downloaded to cache
            state.persist_klines(sym)
            
    log_msg(
        state,
        f"Kline REST pre-fetch complete: {sum(len(v) for v in results.values())} candles loaded."
    )
